#### prefix
set -g prefix C-b
set -g prefix2 C-f

bind C-b send-prefix
bind C-f send-prefix -2

##### indexing
set -g base-index 1 
set -g pane-base-index 1
set -g renumber-windows on

#### behavior
set -g mouse on
set -sg escape-time 10
set -g history-limit 50000

#### terminal/clipboard
set -g default-terminal "tmux-256color"
set -s set-clipboard external

#### reload config
bind r source-file ~/.tmux.conf \; display-message "tmux.conf reloaded"

##### split/new-window with current path
bind '"' split-window -v -c '#{pane_current_path}'
bind % split-window -h -c '#{pane_current_path}'
bind c new-window -c '#{pane_current_path}'

##### no-prefix pane move with Alt + j/i/k/l
bind -n M-j select-pane -L
bind -n M-i select-pane -U
bind -n M-k select-pane -D
bind -n M-l select-pane -R

#### theme
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'samoshkin/tmux-plugin-sysstat'

set -g @sysstat_cpu_view_tmpl '#{cpu.pused}'
set -g @sysstat_mem_view_tmpl '#{mem.pused}'

##### status bar base
set -g status-style 'bg=#2e3440,fg=#eceff4'
set -g status-left-length 40
set -g status-right-length 100

##### left
set -g status-left '#[fg=#b08d57,bg=#4c566a,bold]  #S #[fg=#4c566a,bg=#b08d57,nobold]'

##### windows
set -g window-status-format '#[fg=#88c0d0,bg=#3b4252] #I #[fg=#3b4252,bg=#4c566a]#[fg=#eceff4,bg=#4c566a] #W #[fg=#b08d57,bg=#b08d57]'
set -g window-status-current-format '#[fg=#2e3440,bg=#b08d57,bold] #I #[fg=#b08d57,bg=#b08d57]#[fg=#2e3440,bg=#b08d57,bold] #W #[fg=#b08d57,bg=#2e3440]'

##### right
set -g status-right '#[fg=#4c566a,bg=#2e3440]#[fg=#eceff4,bg=#4c566a] cpu #{sysstat_cpu} | mem #{sysstat_mem} #[fg=#b08d57,bg=#4c566a]#[fg=#2e3440,bg=#b08d57,bold] %Y-%m-%d %H:%M '


run '~/.tmux/plugins/tpm/tpm'
